data_root: /media/nampv1/hdd/var2026/p1/data/raw

scenes:
  public:
    - hcm0031
    - hcm0034
    - HCM0181
    - HCM0193
    - HCM0204
  private:
    - HCM0249
    - HCM0254
    - HCM0276
    - HCM1439
    - HNI0131
    - HNI0265
    - HNI0366
    - HNI0437

seed: 42
exp_name: exp_1
output_root: /media/nampv1/hdd/var2026/p1/data/exp
# submission_root: /path/to/override/submissions/root  # default: <output_root>/submissions/<exp_name>/

gaussian_splatting: /media/nampv1/hdd/var2026/p1/solution/third_party/gaussian-splatting

train:
  iterations: 30000
  sh_degree: 3
  test_interval: 2000
  save_interval: 2000
  checkpoint_interval: 2000
